//created on: May 14, 2020
package com.ftn.webshopdrools.basicDiscount;

//list any import classes here.
import com.ftn.webshop.domain.Order;
import com.ftn.webshop.domain.OrderLine;
import com.ftn.webshop.domain.Item;
import com.ftn.webshop.domain.ItemCategory;
import com.ftn.webshop.domain.DiscountForItem;
import com.ftn.webshop.domain.TypeOfDiscount;


global com.ftn.webshop.services.impl.DiscountForItemServiceImpl discountForItemService;


//declare any global variables here




rule "Basic discount more then 20 items, no mass consumption"
	salience 1000
	activation-group "basic-discounts"
    when
    	$o: Order()
    	$ol: OrderLine(item.category.name  != "Mass consumption", quantity > 20, discountsForItem.empty == true) from $o.getOrderLines()
    then
        System.out.println("Basic discount more then 20 items, no mass consumption");
        discountForItemService.createDiscountForItem(new DiscountForItem($ol, 10.0, $o, TypeOfDiscount.BASIC));
        modify($ol) {
        	addDiscountForItem(new DiscountForItem($ol, 10.0, $o, TypeOfDiscount.BASIC));
        }
        

end


rule "Basic discount more then 5 items, TVs, computers, laptops"
	salience 800
	activation-group "basic-discounts"
    when
    	$o: Order()
    	$ol: OrderLine(item.category.name  == "TV" || item.category.name  == "Desktop computer" || item.category.name  == "Laptop", quantity > 5, discountsForItem.empty == true) from $o.getOrderLines()
    then
        System.out.println("Basic discount more then 5 items, TVs, computers, laptops");
        discountForItemService.createDiscountForItem(new DiscountForItem($ol, 5.0, $o, TypeOfDiscount.BASIC));
        modify($ol) {
        	addDiscountForItem(new DiscountForItem($ol, 5.0, $o, TypeOfDiscount.BASIC));
        }
end

rule "Basic discount more then 7 items, Mass consumption"
	salience 900
	activation-group "basic-discounts"
    when
    	$o: Order()
    	$ol: OrderLine(item.category.name == "Mass consumption", item.price * quantity > 5000, discountsForItem.empty == true) from $o.getOrderLines()
    then
        System.out.println("Basic discount more then 7 items, Mass consumption");
        discountForItemService.createDiscountForItem(new DiscountForItem($ol, 7.0, $o, TypeOfDiscount.BASIC));
        modify($ol) {
        	addDiscountForItem(new DiscountForItem($ol, 7.0, $o, TypeOfDiscount.BASIC));
        }
end




