//created on: May 16, 2020
package com.ftn.webshopdrools.finalDiscountOrderLine;

//list any import classes here.

import com.ftn.webshop.domain.DiscountForItem;
import com.ftn.webshop.domain.Order;
import com.ftn.webshop.domain.OrderLine;
import com.ftn.webshop.domain.Item;
import com.ftn.webshop.domain.ItemCategory;
import com.ftn.webshop.domain.TypeOfDiscountForItem;
import com.ftn.webshop.domain.User;
import com.ftn.webshop.domain.Promotion;

global com.ftn.webshop.services.impl.OrderLineServiceImpl orderLineService;



rule "Check discount for every order line"
	salience -10
    when
    	$o: Order($lines: orderLines)
    	$orderLine: OrderLine($discounts: discountsForItem, $category: item.category, $priceTotal: priceTotal) from $lines
    	Number($sumOfDiscounts: doubleValue) from accumulate(
    		DiscountForItem(
    			$dp: discountPercentage
    		) from $discounts,
    		sum($dp)
    	)
    then
    	 System.out.println("Sum of discounts: " + $sumOfDiscounts + ", item category: " + $category + ", price total is: " + $priceTotal);               
    	 modify($orderLine) {
        	setPercentageDiscount($sumOfDiscounts);
        }     
    	orderLineService.save($orderLine);

end

rule "Check disc"
	salience -100
    when
    	$o: Order($lines: orderLines)
    	$orderLine: OrderLine($percentageDiscount: percentageDiscount > $maxDiscount: item.category.maxPercentageDiscount) from $lines
    then
    	System.out.println("Veci od dozvoljenog: " + $percentageDiscount + ", dozvoljeni: " + $maxDiscount);    	 
    	modify($orderLine) {
        	setPercentageDiscount($maxDiscount);
        }     
    	orderLineService.save($orderLine);
end











